//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMAdmin.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public int ApplicationId { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public string SessionId { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Url { get; set; }
        public string RequestType { get; set; }
        public string ActivityData { get; set; }
        public string Agent { get; set; }
        public string Browser { get; set; }
        public Nullable<System.DateTime> ActivityTime { get; set; }
        public string DeviceName { get; set; }
        public string DeviceMac { get; set; }
        public string PersonnelCode { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual User User { get; set; }
    }
}
