//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMAdmin.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GeneralInformation()
        {
            this.Users = new HashSet<User>();
            this.Users1 = new HashSet<User>();
        }
    
        public int ArmyId { get; set; }
        public string RegimentNo { get; set; }
        public string RegimentNoB { get; set; }
        public string Name { get; set; }
        public string NameB { get; set; }
        public string BjoNo { get; set; }
        public Nullable<int> ParentUnitId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Picture { get; set; }
        public string FatherName { get; set; }
        public string FatherNameB { get; set; }
        public string FatherRegimentNo { get; set; }
        public string MotherNameB { get; set; }
        public string MotherName { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string NationalId { get; set; }
        public bool IsFreedomFighter { get; set; }
        public Nullable<int> RankId { get; set; }
        public Nullable<int> TradeId { get; set; }
        public Nullable<int> BloodGroupId { get; set; }
        public Nullable<int> MedicalCategoryId { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<int> EducationId { get; set; }
        public Nullable<System.DateTime> PresentRankDate { get; set; }
        public Nullable<int> EmploymentTypeIdR { get; set; }
        public Nullable<int> ServiceTermsIdR { get; set; }
        public Nullable<int> CoreId { get; set; }
        public Nullable<int> PoliceVarificationStatusR { get; set; }
        public Nullable<int> PresentDistrictId { get; set; }
        public Nullable<int> MaritalStatusId { get; set; }
        public Nullable<System.DateTime> MarriageDate { get; set; }
        public Nullable<int> PreviousBasicR { get; set; }
        public Nullable<int> CurrentBasic { get; set; }
        public Nullable<System.DateTime> NextIncrementDate { get; set; }
        public Nullable<System.DateTime> ExpectedRetirementDate { get; set; }
        public Nullable<System.DateTime> PayGradeDate { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public string BjoNoB { get; set; }
        public string RdoNo { get; set; }
        public string RdoNoB { get; set; }
        public Nullable<int> IsActiveStatus { get; set; }
        public string MissionStatus { get; set; }
        public string ClassR { get; set; }
        public string CastR { get; set; }
        public string GpfNo { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public bool IsInjuredLiberation { get; set; }
        public bool IsCivil { get; set; }
        public bool IsCs { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public int UpdateNo { get; set; }
        public string JobStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsTribal { get; set; }
        public Nullable<bool> IsCSTTribal { get; set; }
        public Nullable<int> Gender { get; set; }
        public string TinNumber { get; set; }
        public Nullable<bool> IsHomeNearBorder { get; set; }
    
        public virtual SetupUnit SetupUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users1 { get; set; }
    }
}
