//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMAdmin.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SetupUnit()
        {
            this.GeneralInformations = new HashSet<GeneralInformation>();
        }
    
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> SubOrganizationId { get; set; }
        public string UnitCode { get; set; }
        public string UnitFullName { get; set; }
        public Nullable<int> CoreId { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public string UnitNameB { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Israb { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public int UpdateNo { get; set; }
        public string UnitFullNameB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralInformation> GeneralInformations { get; set; }
    }
}
