//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMAdmin.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserPrivileges = new HashSet<UserPrivilege>();
            this.ActivityLogs = new HashSet<ActivityLog>();
        }
    
        public int UserId { get; set; }
        public Nullable<int> ArmyId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int ResourceType { get; set; }
        public string PersonnelCode { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public int UpdateNo { get; set; }
        public string OtpCode { get; set; }
        public Nullable<System.DateTime> OtpGeneratedDate { get; set; }
        public int FailedLoginAttempts { get; set; }
        public bool IsLockOut { get; set; }
        public int UserType { get; set; }
        public bool IsAll { get; set; }
        public string UniteList { get; set; }
    
        public virtual GeneralInformation GeneralInformation { get; set; }
        public virtual GeneralInformation GeneralInformation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPrivilege> UserPrivileges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityLog> ActivityLogs { get; set; }
    }
}
